version: '3.3'

networks:
  basic:

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    ports:
      - '4000:4000'
    expose:
      - '4000'
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./ssl:/root/ssl
    networks:
      - basic