FROM golang:1.14.3-alpine as builder

WORKDIR /go/src/go-grpc

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/client ./cmd/client
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o client ./cmd/client

######## Start a new stage from scratch #######
FROM alpine:3.11.6  

RUN apk --no-cache add portaudio19-dev

WORKDIR /root/

COPY --from=builder /go/src/go-grpc/client .

# Command to run the executable
CMD ["./client"] 